management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    defaults:
      enabled: true
spring:
  application:
    name: ae3zdfg4
  security:
    user:
      name: user
      password: passwd
logging:
  level:
    cn.gomro: debug
